import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

# Configuration constants
MAX_SUBPAGE = 5  # Maximum number of subpages to check
DELAY_RANGE = (0.5, 1.5)  # Request interval range in seconds

# Known conference list
KNOWN_CONFS = {
    # Computer Architecture/Parallel & Distributed Computing/Storage Systems - Class A
    "ppopp": ("ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming", "ppopp"),
    "fast": ("USENIX Conference on File and Storage Technologies", "fast"),
    "dac": ("Design Automation Conference", "dac"),
    "hpca": ("IEEE International Symposium on High Performance Computer Architecture", "hpca"),
    "micro": ("IEEE/ACM International Symposium on Microarchitecture", "micro"),
    "sc": ("International Conference for High Performance Computing, Networking, Storage, and Analysis", "sc"),
    "asplos": ("International Conference on Architectural Support for Programming Languages and Operating Systems", "asplos"),
    "isca": ("International Symposium on Computer Architecture", "isca"),
    "usenix": ("USENIX Annual Technical Conference", "usenix"),
    "eurosys": ("European Conference on Computer Systems", "eurosys"),

    # Computer Architecture/Parallel & Distributed Computing/Storage Systems - Class B
    "cloud": ("ACM Symposium on Cloud Computing", "socc"),
    "spaa": ("ACM Symposium on Parallelism in Algorithms and Architectures", "spaa"),
    "podc": ("ACM Symposium on Principles of Distributed Computing", "podc"),
    "fpga": ("ACM/SIGDA International Symposium on Field-Programmable Gate Arrays", "fpga"),
    "cgo": ("The International Symposium on Code Generation and Optimization", "cgo"),
    "date": ("Design, Automation & Test in Europe", "date"),
    "hotchips": ("Hot Chips: A Symposium on High Performance Chips", "hotchips"),
    "cluster": ("IEEE International Conference on Cluster Computing", "cluster"),
    "iccd": ("International Conference on Computer Design", "iccd"),
    "iccad": ("International Conference on Computer-Aided Design", "iccad"),
    "icdcs": ("IEEE International Conference on Distributed Computing Systems", "icdcs"),
    "codesisss": ("International Conference on Hardware/Software Co-design and System Synthesis", "codesisss"),
    "hipc": ("International Conference on High Performance and Embedded Architectures and Compilers", "hipeac"),
    "sigmetrics": ("International Conference on Measurement and Modeling of Computer Systems", "sigmetrics"),
    "ieeepact": ("International Conference on Parallel Architectures and Compilation Techniques", "pact"),
    "icpp": ("International Conference on Parallel Processing", "icpp"),
    "ics": ("International Conference on Supercomputing", "ics"),
    "vee": ("International Conference on Virtual Execution Environments", "vee"),
    "ipps": ("IEEE International Parallel & Distributed Processing Symposium", "ipdps"),
    "performance": ("International Symposium on Computer Performance, Modeling, Measurements and Evaluation", "performance"),
    "hpdc": ("The International ACM Symposium on High-Performance Parallel and Distributed Computing", "hpdc"),
    "itc": ("International Test Conference", "itc"),
    "lisa": ("Large Installation System Administration Conference", "lisa"),
    "mss": ("Mass Storage Systems and Technologies", "msst"),
    "rtas": ("IEEE Real-Time and Embedded Technology and Applications Symposium", "rtas"),
    "europar": ("European Conference on Parallel and Distributed Computing", "europar"),

    # Computer Architecture/Parallel & Distributed Computing/Storage Systems - Class C
    "cf": ("ACM International Conference on Computing Frontiers", "cf"),
    "systor": ("ACM International Systems and Storage Conference", "systor"),
    "nocs": ("ACM/IEEE International Symposium on Networks-on-Chip", "nocs"),
    "asap": ("IEEE International Conference on Application-Specific Systems, Architectures, and Processors", "asap"),
    "aspdac": ("Asia and South Pacific Design Automation Conference", "aspdac"),
    "ets": ("IEEE European Test Symposium", "ets"),
    "fpl": ("International Conference on Field-Programmable Logic and Applications", "fpl"),
    "fccm": ("IEEE Symposium on Field-Programmable Custom Computing Machines", "fccm"),
    "glsvlsi": ("Great Lakes Symposium on VLSI", "glvlsi"),
    "ats": ("IEEE Asian Test Symposium", "ats"),
    "hpcc": ("IEEE International Conference on High Performance Computing and Communications", "hpcc"),
    "hipc": ("IEEE International Conference on High Performance Computing, Data and Analytics", "hipc"),
    "mascots": ("International Symposium on Modeling, Analysis, and Simulation of Computer and Telecommunication Systems", "mascots"),
    "ispa": ("IEEE International Symposium on Parallel and Distributed Processing with Applications", "ispa"),
    "ccgrid": ("IEEE/ACM International Symposium on Cluster, Cloud and Grid Computing", "ccgrid"),
    "npc": ("IFIP International Conference on Network and Parallel Computing", "npc"),
    "ica3pp": ("International Conference on Algorithms and Architectures for Parallel Processing", "ica3pp"),
    "cases": ("International Conference on Compilers, Architectures, and Synthesis for Embedded Systems", "cases"),
    "fpt": ("International Conference on Field-Programmable Technology", "icfpt"),
    "icpads": ("International Conference on Parallel and Distributed Systems", "icpads"),
    "iscas": ("IEEE International Symposium on Circuits and Systems", "iscas"),
    "islped": ("International Symposium on Low Power Electronics and Design", "islped"),
    "ispd": ("International Symposium on Physical Design", "ispd"),
    "hoti": ("IEEE Symposium on High-Performance Interconnects", "hoti"),
    "vts": ("IEEE VLSI Test Symposium", "vts"),
    "itc-asia": ("International Test Conference in Asia", "itc-asia"),

    # Computer Networks - Class A
    "sigcomm": ("ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication", "sigcomm"),
    "mobicom": ("ACM International Conference on Mobile Computing and Networking", "mobicom"),
    "infocom": ("IEEE International Conference on Computer Communications", "infocom"),
    "nsdi": ("Symposium on Network System Design and Implementation", "nsdi"),

    # Computer Networks - Class B
    "sensys": ("ACM Conference on Embedded Networked Sensor Systems", "sensys"),
    "conext": ("ACM International Conference on Emerging Networking Experiments and Technologies", "conext"),
    "secon": ("IEEE International Conference on Sensing, Communication, and Networking", "secon"),
    "ipsn": ("International Conference on Information Processing in Sensor Networks", "ipsn"),
    "mobisys": ("ACM International Conference on Mobile Systems, Applications, and Services", "mobisys"),
    "icnp": ("IEEE International Conference on Network Protocols", "icnp"),
    "mobihoc": ("International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing", "mobihoc"),
    "nossdav": ("International Workshop on Network and Operating System Support for Digital Audio and Video", "nossdav"),
    "iwqos": ("IEEE/ACM International Workshop on Quality of Service", "iwqos"),
    "imc": ("ACM Internet Measurement Conference", "imc"),

    # Computer Networks - Class C
    "ancs": ("ACM/IEEE Symposium on Architectures for Networking and Communication Systems", "ancs"),
    "apnoms": ("Asia-Pacific Network Operations and Management Symposium", "apnoms"),
    "forte": ("International Conference on Formal Techniques for Distributed Objects, Components, and Systems", "forte"),
    "lcn": ("IEEE Conference on Local Computer Networks", "lcn"),
    "globecom": ("IEEE Global Communications Conference", "globecom"),
    "icc": ("IEEE International Conference on Communications", "icc"),
    "icccn": ("IEEE International Conference on Computer Communications and Networks", "icccn"),
    "mass": ("IEEE International Conference on Mobile Adhoc and Sensor Systems", "mass"),
    "p2p": ("IEEE International Conference on Peer-to-Peer Computing", "p2p"),
    "ipccc": ("IEEE International Performance Computing and Communications Conference", "ipccc"),
    "wowmom": ("IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks", "wowmom"),
    "iscc": ("IEEE Symposium on Computers and Communications", "iscc"),
    "wcnc": ("IEEE Wireless Communications and Networking Conference", "wcnc"),
    "networking": ("IFIP International Conferences on Networking", "networking"),
    "im": ("IFIP/IEEE International Symposium on Integrated Network Management", "im"),
    "msn": ("International Conference on Mobility, Sensing and Networking", "msn"),
    "mswim": ("International Conference on Modeling, Analysis and Simulation of Wireless and Mobile Systems", "mswim"),
    "wasa": ("International Conference on Wireless Algorithms, Systems, and Applications", "wasa"),
    "hotnets": ("ACM The Workshop on Hot Topics in Networks", "hotnets"),
    "apnet": ("Asia-Pacific Workshop on Networking", "apnet"),

    # Network & Information Security - Class A
    "ccs": ("ACM Conference on Computer and Communications Security", "ccs"),
    "eurocrypt": ("International Conference on the Theory and Applications of Cryptographic Techniques", "eurocrypt"),
    "sp": ("IEEE Symposium on Security and Privacy", "sp"),
    "crypto": ("International Cryptology Conference", "crypto"),
    "uss": ("USENIX Security Symposium", "uss"),
    "ndss": ("Network and Distributed System Security Symposium", "ndss"),

    # Network & Information Security - Class B
    "acsac": ("Annual Computer Security Applications Conference", "acsac"),
    "asiacrypt": ("Annual International Conference on the Theory and Application of Cryptology and Information Security", "asiacrypt"),
    "esorics": ("European Symposium on Research in Computer Security", "esorics"),
    "sigsoft": ("Fast Software Encryption", "fse"),
    "csfw": ("IEEE Computer Security Foundations Workshop", "csf"),
    "srds": ("IEEE International Symposium on Reliable Distributed Systems", "srds"),
    "ches": ("International Conference on Cryptographic Hardware and Embedded Systems", "ches"),
    "dsn": ("International Conference on Dependable Systems and Networks", "dsn"),
    "raid": ("International Symposium on Recent Advances in Intrusion Detection", "raid"),
    "pkc": ("International Workshop on Practice and Theory in Public Key Cryptography", "pkc"),
    "tcc": ("Theory of Cryptography Conference", "tcc"),

    # Network & Information Security - Class C
    "wisec": ("ACM Conference on Security and Privacy in Wireless and Mobile Networks", "wisec"),
    "sacmat": ("ACM Symposium on Access Control Models and Technologies", "sacmat"),
    "drm": ("ACM Workshop on Digital Rights Management", "drm"),
    "ih": ("ACM Workshop on Information Hiding and Multimedia Security", "ihmmsec"),
    "acns": ("International Conference on Applied Cryptography and Network Security", "acns"),
    "asiaccs": ("ACM Asia Conference on Computer and Communications Security", "asiaccs"),
    "acisp": ("Australasia Conference on Information Security and Privacy", "acisp"),
    "ct-rsa": ("The Cryptographer's Track at RSA Conference", "ctrsa"),
    "dimva": ("Conference on Detection of Intrusions and Malware & Vulnerability Assessment", "dimva"),
    "dfrws": ("Digital Forensic Research Workshop", "dfrws"),
    "fc": ("Financial Cryptography and Data Security", "fc"),
    "trustcom": ("IEEE International Conference on Trust, Security and Privacy in Computing and Communications", "trustcom"),

    # Software Engineering/System Software/Programming Languages - Class A
    "pldi": ("ACM SIGPLAN Conference on Programming Language Design and Implementation", "pldi"),
    "popl": ("ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages", "popl"),
    "fse_esec": ("ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering", "sigsoft"),
    "sosp": ("ACM Symposium on Operating Systems Principles", "sosp"),
    "oopsla": ("Conference on Object-Oriented Programming Systems, Languages, and Applications", "oopsla"),
    "kbse": ("International Conference on Automated Software Engineering", "ase"),
    "icse": ("International Conference on Software Engineering", "icse"),
    "issta": ("International Symposium on Software Testing and Analysis", "issta"),
    "osdi": ("USENIX Symposium on Operating Systems Design and Implementation", "osdi"),
    "fm": ("International Symposium on Formal Methods", "fm"),

    # Software Engineering/System Software/Programming Languages - Class B
    "ecoop": ("European Conference on Object-Oriented Programming", "ecoop"),
    "eptcs": ("European Joint Conferences on Theory and Practice of Software", "eptcs"),
    "icpc": ("IEEE International Conference on Program Comprehension", "icpc"),
    "re": ("IEEE International Requirements Engineering Conference", "re"),
    "caise": ("International Conference on Advanced Information Systems Engineering", "caise"),
    "icfp": ("ACM SIGPLAN International Conference on Function Programming", "scheme"),
    "lctrts": ("ACM SIGPLAN/SIGBED International Conference on Languages, Compilers and Tools for Embedded Systems", "lctes"),
    "models": ("ACM/IEEE International Conference on Model Driven Engineering Languages and Systems", "models"),
    "cp": ("International Conference on Principles and Practice of Constraint Programming", "cp"),
    "icsoc": ("International Conference on Service Oriented Computing", "icsoc"),
    "saner": ("IEEE International Conference on Software Analysis, Evolution, and Reengineering", "saner"),
    "icsm": ("International Conference on Software Maintenance and Evolution", "icsme"),
    "vmcai": ("International Conference on Verification, Model Checking, and Abstract Interpretation", "vmcai"),
    "icws": ("IEEE International Conference on Web Services", "icws"),
    "middleware": ("International Middleware Conference", "middleware"),
    "sas": ("International Static Analysis Symposium", "sas"),
    "esem": ("International Symposium on Empirical Software Engineering and Measurement", "esem"),
    "issre": ("IEEE International Symposium on Software Reliability Engineering", "issre"),
    "hotos": ("USENIX Workshop on Hot Topics in Operating Systems", "hotos"),

    # Software Engineering/System Software/Programming Languages - Class C
    "pepm": ("ACM SIGPLAN Workshop on Partial Evaluation and Program Manipulation", "pepm"),
    "paste": ("ACM SIGPLAN-SIGSOFT Workshop on Program Analysis for Software Tools and Engineering", "paste"),
    "aplas": ("Asian Symposium on Programming Languages and Systems", "aplas"),
    "apsec": ("Asia-Pacific Software Engineering Conference", "apsec"),
    "ease": ("International Conference on Evaluation and Assessment in Software Engineering", "ease"),
    "iceccs": ("International Conference on Engineering of Complex Computer Systems", "iceccs"),
    "icst": ("IEEE International Conference on Software Testing, Verification and Validation", "icst"),
    "ispass": ("IEEE International Symposium on Performance Analysis of Systems and Software", "ispass"),
    "scam": ("IEEE International Working Conference on Source Code Analysis and Manipulation", "scam"),
    "compsac": ("International Computer Software and Applications Conference", "compsac"),
    "icfem": ("International Conference on Formal Engineering Methods", "icfem"),
    "ieeescc": ("IEEE International Conference on Services Computing", "scc"),
    "ispw": ("International Conference on Software and System Process", "icssp"),
    "seke": ("International Conference on Software Engineering and Knowledge Engineering", "seke"),
    "qrs": ("International Conference on Software Quality, Reliability and Security", "qrs"),
    "icsr": ("International Conference on Software Reuse", "icsr"),
    "icwe": ("International Conference on Web Engineering", "icwe"),
    "spin": ("International Symposium on Model Checking of Software", "spin"),
    "atva": ("International Symposium on Automated Technology for Verification and Analysis", "atva"),
    "lopstr": ("International Symposium on Logic-based Program Synthesis and Transformation", "lopstr"),
    "tase": ("Theoretical Aspects of Software Engineering Conference", "tase"),
    "msr": ("Mining Software Repositories", "msr"),
    "refsq": ("Requirements Engineering: Foundation for Software Quality", "refsq"),
    "wicsa": ("Working IEEE/IFIP Conference on Software Architecture", "wicsa"),
    "internetware": ("Asia-Pacific Symposium on Internetware", "internetware"),
    "rv": ("International Conference on Runtime Verification", "rv"),

    # Databases/Data Mining/Content Retrieval - Class A
    "sigmod": ("ACM SIGMOD Conference", "sigmod"),
    "kdd": ("ACM SIGKDD Conference on Knowledge Discovery and Data Mining", "kdd"),
    "icde": ("IEEE International Conference on Data Engineering", "icde"),
    "sigir": ("International ACM SIGIR Conference on Research and Development in Information Retrieval", "sigir"),
    "vldb": ("International Conference on Very Large Data Bases", "vldb"),

    # Databases/Data Mining/Content Retrieval - Class B
    "cikm": ("ACM International Conference on Information and Knowledge Management", "cikm"),
    "wsdm": ("ACM International Conference on Web Search and Data Mining", "wsdm"),
    "pods": ("ACM SIGMOD-SIGACT-SIGAI Symposium on Principles of Database Systems", "pods"),
    "dasfaa": ("International Conference on Database Systems for Advanced Applications", "dasfaa"),
    "pkdd": ("European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases", "pkdd"),
    "semweb": ("IEEE International Semantic Web Conference", "iswc"),
    "icdm": ("IEEE International Conference on Data Mining", "icdm"),
    "icdt": ("International Conference on Database Theory", "icdt"),
    "edbt": ("International Conference on Extending Database Technology", "edbt"),
    "cidr": ("Conference on Innovative Data Systems Research", "cidr"),
    "sdm": ("SIAM International Conference on Data Mining", "sdm"),
    "recsys": ("ACM Conference on Recommender Systems", "recsys"),

    # Databases/Data Mining/Content Retrieval - Class C
    "apweb": ("Asia Pacific Web Conference", "apweb"),
    "dexa": ("International Conference on Database and Expert System Applications", "dexa"),
    "ecir": ("European Conference on Information Retrieval", "ecir"),
    "eswc": ("Extended Semantic Web Conference", "eswc"),
    "webdb": ("International Workshop on Web and Databases", "webdb"),
    "er": ("International Conference on Conceptual Modeling", "er"),
    "mdm": ("International Conference on Mobile Data Management", "mdm"),
    "ssdbm": ("International Conference on Scientific and Statistical Database Management", "ssdbm"),
    "waim": ("International Conference on Web Age Information Management", "waim"),
    "ssd": ("International Symposium on Spatial and Temporal Databases", "sstd"),
    "pakdd": ("Pacific-Asia Conference on Knowledge Discovery and Data Mining", "pakdd"),
    "wise": ("Web Information Systems Engineering", "wise"),
    "adma": ("International Conference on Advanced Data Mining and Applications", "adma"),

    # Computer Science Theory - Class A
    "stoc": ("ACM Symposium on the Theory of Computing", "stoc"),
    "soda": ("ACM-SIAM Symposium on Discrete Algorithms", "soda"),
    "cav": ("International Conference on Computer Aided Verification", "cav"),
    "focs": ("IEEE Annual Symposium on Foundations of Computer Science", "focs"),
    "lics": ("ACM/IEEE Symposium on Logic in Computer Science", "lics"),

    # Computer Science Theory - Class B
    "compgeom": ("International Symposium on Computational Geometry", "compgeom"),
    "esa": ("European Symposium on Algorithms", "esa"),
    "coco": ("Conference on Computational Complexity", "coco"),
    "icalp": ("International Colloquium on Automata, Languages and Programming", "icalp"),
    "cade": ("International Conference on Automated Deduction", "cade"),
    "concur": ("International Conference on Concurrency Theory", "concur"),
    "hybrid": ("International Conference on Hybrid Systems: Computation and Control", "hscc"),
    "sat": ("International Conference on Theory and Applications of Satisfiability Testing", "sat"),
    "cocoon": ("International Computing and Combinatorics Conference", "cocoon"),

    # Computer Science Theory - Class C
    "csl": ("Computer Science Logic", "csl"),
    "fmcad": ("Formal Methods in Computer-Aided Design", "fmcad"),
    "fsttcs": ("Foundations of Software Technology and Theoretical Computer Science", "fsttcs"),
    "dsaa": ("IEEE International Conference on Data Science and Advanced Analytics", "dsaa"),
    "ictac": ("International Colloquium on Theoretical Aspects of Computing", "ictac"),
    "ipco": ("International Conference on Integer Programming and Combinatorial Optimization", "ipco"),
    "rta": ("International Conference on Rewriting Techniques and Applications", "rta"),
    "isaac": ("International Symposium on Algorithms and Computation", "isaac"),
    "mfcs": ("International Conference on Mathematical Foundations of Computer Science", "mfcs"),
    "stacs": ("Symposium on Theoretical Aspects of Computer Science", "stacs"),
    "setta": ("Software Engineering: Theories, Tools, and International Symposium on Dependable Applications", "setta"),

    # Computer Graphics & Multimedia - Class A
    "mm": ("ACM International Conference on Multimedia", "mm"),
    "siggraph": ("ACM Special Interest Group on Computer Graphics", "siggraph"),
    "vr": ("IEEE Virtual Reality", "vr"),
    "visualization": ("IEEE Visualization Conference", "visualization"),

    # Computer Graphics & Multimedia - Class B
    "mir": ("ACM SIGMM International Conference on Multimedia Retrieval", "icmr"),
    "si3d": ("ACM SIGGRAPH Symposium on Interactive 3D Graphics and Games", "si3d"),
    "sca": ("ACM SIGGRAPH/Eurographics Symposium on Computer Animation", "sca"),
    "dcc": ("Data Compression Conference", "dcc"),
    "eurographics": ("Annual Conference of the European Association for Computer Graphics", "eg-short"),
    "vissym": ("Eurographics Conference on Visualization", "eurovis"),
    "sgp": ("Eurographics Symposium on Geometry Processing", "sgp"),
    "rt": ("Eurographics Symposium on Rendering", "egsr"),
    "icassp": ("IEEE International Conference on Acoustics, Speech and Signal Processing", "icassp"),
    "icmcs": ("IEEE International Conference on Multimedia & Expo", "icme"),
    "ismar": ("International Symposium on Mixed and Augmented Reality", "ismar"),
    "pg": ("Pacific Conference on Computer Graphics and Applications", "pg"),
    "sma": ("Symposium on Solid and Physical Modeling", "spm"),

    # Computer Graphics & Multimedia - Class C
    "vrst": ("ACM Symposium on Virtual Reality Software and Technology", "vrst"),
    "ca": ("International Conference on Computer Animation and Social Agents", "casa"),
    "cgi": ("Computer Graphics International", "cgi"),
    "interspeech": ("Conference of the International Speech Communication Association", "interspeech"),
    "gmp": ("Geometric Modeling and Processing", "gmp"),
    "pacificvis": ("IEEE Pacific Visualization Symposium", "pacificvis"),
    "3dim": ("International Conference on 3D Vision", "3dv"),
    "cad_graphics": ("International Conference on Computer-Aided Design and Computer Graphics", "cadgraphics"),
    "icip": ("IEEE International Conference on Image Processing", "icip"),
    "mmm": ("International Conference on Multimedia Modeling", "mmm"),
    "mmasia": ("ACM Multimedia Asia", "mmasia"),
    "smi": ("Shape Modeling International", "smi"),
    "vric": ("International Conference on Virtual Reality and Visualization", "vric"),
    "cvm": ("Computational Visual Media", "cvm"),
    "prcv": ("Chinese Conference on Pattern Recognition and Computer Vision", "prcv"),

    # Artificial Intelligence - Class A
    "aaai": ("AAAI Conference on Artificial Intelligence", "aaai"),
    "nips": ("Conference on Neural Information Processing Systems", "neurips"),
    "acl": ("Annual Meeting of the Association for Computational Linguistics", "acl"),
    "cvpr": ("IEEE/CVF Computer Vision and Pattern Recognition Conference", "cvpr"),
    "iccvw": ("International Conference on Computer Vision", "iccvw"),
    "icml": ("International Conference on Machine Learning", "icml"),
    "ijcai": ("International Joint Conference on Artificial Intelligence", "ijcai"),

    # Artificial Intelligence - Class B
    "colt": ("Annual Conference on Computational Learning Theory", "colt"),
    "emnlp": ("Conference on Empirical Methods in Natural Language Processing", "emnlp"),
    "ecai": ("European Conference on Artificial Intelligence", "ecai"),
    "eccv": ("European Conference on Computer Vision", "eccv"),
    "icra": ("IEEE International Conference on Robotics and Automation", "icra"),
    "icaps": ("International Conference on Automated Planning and Scheduling", "icaps"),
    "iccbr": ("International Conference on Case-Based Reasoning", "iccbr"),
    "coling": ("International Conference on Computational Linguistics", "coling"),
    "kr": ("International Conference on Principles of Knowledge Representation and Reasoning", "kr"),
    "uai": ("Conference on Uncertainty in Artificial Intelligence", "uai"),
    "atal": ("International Joint Conference on Autonomous Agents and Multi-agent Systems", "aamas"),
    "ppsn": ("Parallel Problem Solving from Nature", "ppsn"),
    "naacl": ("North American Chapter of the Association for Computational Linguistics", "naacl"),

    # Artificial Intelligence - Class C
    "aistats": ("International Conference on Artificial Intelligence and Statistics", "aistats"),
    "accv": ("Asian Conference on Computer Vision", "accv"),
    "acml": ("Asian Conference on Machine Learning", "acml"),
    "bmvc": ("British Machine Vision Conference", "bmvc"),
    "nlpcc": ("CCF International Conference on Natural Language Processing and Chinese Computing", "nlpcc"),
    "conll": ("Conference on Computational Natural Language Learning", "conll"),
    "gecco": ("Genetic and Evolutionary Computation Conference", "gecco"),
    "ictai": ("IEEE International Conference on Tools with Artificial Intelligence", "ictai"),
    "iros": ("IEEE/RSJ International Conference on Intelligent Robots and Systems", "iros"),
    "alt": ("International Conference on Algorithmic Learning Theory", "alt"),
    "icann": ("International Conference on Artificial Neural Networks", "icann"),
    "fgr": ("IEEE International Conference on Automatic Face and Gesture Recognition", "fg"),
    "icdar": ("International Conference on Document Analysis and Recognition", "icdar"),
    "ilp": ("International Conference on Inductive Logic Programming", "ilp"),
    "ksem": ("International Conference on Knowledge Science, Engineering and Management", "ksem"),
    "iconip": ("International Conference on Neural Information Processing", "iconip"),
    "icpr": ("International Conference on Pattern Recognition", "icpr"),
    "icb": ("International Joint Conference on Biometrics", "ijcb"),
    "ijcnn": ("International Joint Conference on Neural Networks", "ijcnn"),
    " pricai": ("Pacific Rim International Conference on Artificial Intelligence", "pricai"),

    # Human-Computer Interaction & Ubiquitous Computing - Class A
    "huc": ("ACM International Joint Conference on Pervasive and Ubiquitous Computing", "ubicomp"),
    "uist": ("ACM Symposium on User Interface Software and Technology", "uist"),

    # Human-Computer Interaction & Ubiquitous Computing - Class B
    "group": ("ACM International Conference on Supporting Group Work", "group"),
    "iui": ("ACM International Conference on Intelligent User Interfaces", "iui"),
    "tabletop": ("ACM International Conference on Interactive Tabletops and Surfaces", "iss"),
    "ecscw": ("European Conference on Computer Supported Cooperative Work", "ecscw"),
    "percom": ("IEEE International Conference on Pervasive Computing and Communications", "percom"),
    "mhci": ("ACM International Conference on Mobile Human-Computer Interaction", "mhci"),
    "icwsm": ("The International AAAI Conference on Web and Social Media", "icwsm"),

    # Human-Computer Interaction & Ubiquitous Computing - Class C
    "acmdis": ("ACM SIGCHI Conference on Designing Interactive Systems", "acmdis"),
    "icmi": ("ACM International Conference on Multimodal Interaction", "icmi"),
    "assets": ("International ACM SIGACCESS Conference on Computers and Accessibility", "assets"),
    "graphicsinterface": ("Graphics Interface", "graphicsinterface"),
    "uic": ("IEEE International Conference on Ubiquitous Intelligence and Computing", "uic"),
    "haptics": ("IEEE World Haptics Conference", "haptics"),
    "interact": ("International Conference on Human-Computer Interaction of International Federation for Information Processing", "interact"),
    "acmidc": ("ACM Interaction Design and Children", "idc"),
    "colcom": ("International Conference on Collaborative Computing: Networking, Applications and Worksharing", "colcom"),
    "cscwd": ("International Conference on Computer Supported Cooperative Work in Design", "cscwd"),
    "coopis": ("International Conference on Cooperative Information Systems", "coopis"),
    "mobiquitous": ("International Conference on Mobile and Ubiquitous Systems: Computing, Networking and Services", "mobiquitous"),
    "avi": ("International Working Conference on Advanced Visual Interfaces", "avi"),

    # Interdisciplinary/Comprehensive/Emerging - Class A
    "www": ("International World Wide Web Conference", "www"),
    "rtss": ("IEEE Real-Time Systems Symposium", "rtss"),
    "wine": ("Conference on Web and Internet Economics", "wine"),

    # Interdisciplinary/Comprehensive/Emerging - Class B
    "cogsci": ("Annual Meeting of the Cognitive Science Society", "cogsci"),
    "bibm": ("IEEE International Conference on Bioinformatics and Biomedicine", "bibm"),
    "emsoft": ("International Conference on Embedded Software", "emsoft"),
    "ismb": ("International Conference on Intelligent Systems for Molecular Biology", "biolink"),
    "recomb": ("Annual International Conference on Research in Computational Molecular Biology", "recomb"),
    "miccai": ("International Conference on Medical Image Computing and Computer-Assisted Intervention", "miccai"),

    # Interdisciplinary/Comprehensive/Emerging - Class C
    "amia": ("American Medical Informatics Association Annual Symposium", "amia"),
    "apbc": ("Asia Pacific Bioinformatics Conference", "apbc"),
    "bigdataconf": ("IEEE International Conference on Big Data", "bigdataconf"),
    "ieeecloud": ("IEEE International Conference on Cloud Computing", "ieeecloud"),
    "smc": ("IEEE International Conference on Systems, Man, and Cybernetics", "smc"),
    "cosit": ("International Conference on Spatial Information Theory", "cosit"),
    "isbra": ("International Symposium on Bioinformatics Research and Applications", "isbra"),
    "sagt": ("International Symposium on Algorithmic Game Theory", "sagt"),
    "sigspatial": ("ACM Special Interest Group on Spatial Information", "sigspatial"),
    "icic": ("International Conference on Intelligent Computing", "icic")
}

# Configure session with retry strategy
session = requests.Session()
retry_strategy = Retry(
    total=3,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504]
)
adapter = HTTPAdapter(max_retries=retry_strategy)
session.mount("https://", adapter)
session.mount("http://", adapter)